### ISSUE TITLE
Specific username breaks 'log ins' 

### ISSUE THREAD

**Issue by connerledbetter1** [uncheckederror/Ocean2Ocean#8]
|-|  __
jgs  |=| [Ll]
     "^" ====`o

**Comment by uncheckederror** [comment]
This is a fun little bug.

Here is the T-SQL query that gets executed in application code:

`SELECT [EntryId], [Email], [JourneyName], [Steps], [Created] FROM [dbo].[Entries] WHERE [Email] LIKE '%|-| __ jgs |=| [Ll] \"^\" ====``o%' ORDER BY [Created] DESC`

It returns no results.

But if you drop the leading and trailing wild card chars and look for direct equality rather than fuzzy equality with the LIKE operator it works perfectly.

`SELECT [EntryId], [Email], [JourneyName], [Steps], [Created] FROM [dbo].[Entries] WHERE [Email] = '|-| __ jgs |=| [Ll] "^" ====``o' ORDER BY [Created] DESC`

The solution here is to check if the first query returned any results. If it did not, then we execute the second query looking for direct equality.

**Comment by uncheckederror** [comment]
I have verified that this bug is fixed in production.
